- name: create local admin users
  user:
    append: yes
    groups: sudo
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    shell: /bin/bash
  with_items:
    - username: japsu
      password: $6$dFaORqhsGMSZ$Y5zvRLc0Q.8qgUY7Wv26f8y.OnfCHwe9wM8qeum0RzLnQWzko75Nq2wxaS481OfUUaMKDbWOs1viI9qfyXKQ4.

- name: set local admin private keys
  authorized_key: >
    user={{ item.username }}
    key="{{ item.key }}"
  with_items:
    - username: japsu
      key: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAvCmc0uCpmMb/zHVCF7LFoxZpTnTbR26rGZTNpSrjtq2R75Lal0GoSNyDLwRwcUig2kBzYgrchKZxGi6K90AjRR4cpoeImxftEylieRFP6VMyV64lK7fnYWEH5PUf7izWbV5OEBgQOl63R6UnAf0sQ6KuqdnbixDoJrltl5xvvCuJurikh7kGWrv4+gop0OUdV8Ja+xjpASQSBRXqM7kwn83wKJ/ic8xHiwTp1P/UQTxbNgaOCkD+VHstKxmE8KtMKuLKOmVU1KOYi3TgSfqs8jO/eRDegThlsiejuV/FQGZa/SXWuqZlM8vcsyGHnG0JmOOaoCdo1pplKWoSyN2UDQ== japsu@navitas-20150803
    - username: japsu
      key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD2J0XDtp4uR/W0Z6kf+0TXZtj+8If1p1kSg0QkYEiTKIaiYHwQTTkfrKVD5OTJYQGjvWBGFow7vJLFaahWkNj2/QAbfluQ/4B83SBGVsgsvXWIJ3kfq/8Fc00+L13w8N1zTT0RVOrnokGTkgXOOjTj7Op8Dhye0AhAS1HnZKTUs60wZ0qPdG8cuBH0W24bSMz44LZ/5PnXn/5W5z2pb+Bw0ZjzJ9VvqL6I97jpn9pFZg04SmMFj9e0p70O72gBjvJbAkE8Nilqr3z4WKS9Vey2K4/p78LsdMiEyJqGf5L5En81J9aN83OWMkYVYYrVMqjeY7av1wXfNzCBd7ccFeJFab8TQvVqp1gnhLCIxyKMA8hN3aF/6nsVcji5nFkiBugVuBnBvf7g90rAU+3uz6UdkQRJoIY9u83cMY5jd4xZVgzVqj9HerIkJUq+Lxd8090qIIy3viKiAbkIHt+pzYHEy/tSGQMY/lfUUQJjPTRBSERtCT+F9R1QHKH7q7mKUCRSOEV3+AZYgyG3T7LWDtuEg+i0rsJGsmVpUMn6Z4YRmF7OYwnm3j/4zdyp7f3/o67U/pkhHn9IIzUTy6IyX+xIhz5opBk9LPvUSdaGuQaeJl8d7yjJMNO54FGfic1OqTmD3nCMcIDu9RwyBfDodDr/mL8d1tMHToWf44bs60u4YQ== japsu@myrmidon-20160308
    - username: japsu
      key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCbeknGVhGeEaA+aiRJDj9isKdtoN3naqTq/Kql/8zukk2rz8HLMLNvPE9FJ/eUt6zwY29palhhjI5n/l2CIV5b75Q/wco23L9vzgAPnjAd7aaE2OqrIiCbl4rEyoLyzdvFbvx7IlP6AG48oT5fuHSOrbx6v3vOQURg7ekqgNxX7x+G55zIXQt4GbaYZ+NXeIlWnzfEfg72WUxT0SONZ+PNm67nbT8Y0Y2trqFEoVOIiU34P+4VJFTfv2fxKtCSw3Za56KDTkchE57DiforuxdQbFDU/806JUW/PguDD7xYWiiFursB708EVmqU4RpJ5Mqx7w82R3+4cqvywI0SMYdp japsu@comet-20141003
